[package]
name = "aoc17"
version = "0.1.0"
authors = ["Yury FEDOROV <yury.fedorov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
linked-list = "0.0.3"